export const MAX_SUBMISSION_FIELDS = 100;
export const MAX_SHORT_TEXT_LENGTH = 10_000;
export const MAX_LONG_TEXT_LENGTH = 10_000;
export const MAX_EMAIL_LENGTH = 320;
export const MAX_SUBMISSION_TEXT_LENGTH = 64_000;
